### ISSUE TITLE
能否支持复制粘贴本地文件？

### ISSUE THREAD

**Issue by Edenharder** [Cubernet/insert-img#1]
有时要用到的不仅仅是截图，而是本地的一些图片文件。

**Comment by Cubernet** [comment]
最近有点忙，一直没有维护了。你提的这个需求的确存在，我目前是这样解决的：打开图片，然后ctrl+c复制，然后再用插件粘贴。虽然多了打开图片这个步骤，不过可以暂时规避下这个问题。

**Comment by Edenharder** [comment]
@Cubernet 谢谢你的回复！
